workflows:
  flutter-web:
    name: Flutter Web Workflow
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build web release
        script: flutter build web --release
    artifacts:
      - build/web/**
